#!/bin/bash
#
# Birilium Node - Digital Ocean Auto-Deploy Script
# This script automates the deployment of a Birilium seed node
#
# Usage: bash deploy-digitalocean.sh YOUR_SERVER_IP
#

set -e  # Exit on any error

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Birilium Node - Digital Ocean Deploy${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Check if IP provided
if [ -z "$1" ]; then
    echo -e "${RED}Error: Server IP address required${NC}"
    echo "Usage: bash deploy-digitalocean.sh YOUR_SERVER_IP"
    echo "Example: bash deploy-digitalocean.sh 142.93.123.45"
    exit 1
fi

SERVER_IP=$1
echo -e "${GREEN}Target Server: ${SERVER_IP}${NC}"
echo ""

# Check if we can connect
echo -e "${BLUE}Step 1: Testing SSH connection...${NC}"
ssh -o ConnectTimeout=10 root@${SERVER_IP} "echo 'SSH connection successful'" || {
    echo -e "${RED}Failed to connect to ${SERVER_IP}${NC}"
    echo "Make sure:"
    echo "1. Your server is running"
    echo "2. SSH key is configured"
    echo "3. You can access: ssh root@${SERVER_IP}"
    exit 1
}

echo -e "${GREEN}✓ SSH connection OK${NC}"
echo ""

# Deploy the node
echo -e "${BLUE}Step 2: Installing dependencies...${NC}"
ssh root@${SERVER_IP} << 'ENDSSH'
set -e

# Update system
echo "Updating system packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get upgrade -y

# Install Node.js
echo "Installing Node.js 20.x..."
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt-get install -y nodejs

# Install MongoDB
echo "Installing MongoDB..."
curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | \
   gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor

echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | \
   tee /etc/apt/sources.list.d/mongodb-org-7.0.list

apt-get update
apt-get install -y mongodb-org

# Start MongoDB
systemctl start mongod
systemctl enable mongod

# Install PM2
echo "Installing PM2..."
npm install -g pm2

# Install Git
apt-get install -y git

echo "✓ Dependencies installed"
ENDSSH

echo -e "${GREEN}✓ Dependencies installed${NC}"
echo ""

# Clone and setup
echo -e "${BLUE}Step 3: Cloning Birilium repository...${NC}"
ssh root@${SERVER_IP} << 'ENDSSH'
set -e

# Remove old installation if exists
if [ -d "Birilium" ]; then
    echo "Removing old installation..."
    rm -rf Birilium
fi

# Clone repository
echo "Cloning from GitHub..."
git clone https://github.com/ilan84levi/Birilium.git
cd Birilium/wallet/node-backend

# Install dependencies
echo "Installing Node dependencies..."
npm install --production

echo "✓ Repository cloned and dependencies installed"
ENDSSH

echo -e "${GREEN}✓ Repository cloned${NC}"
echo ""

# Configure environment
echo -e "${BLUE}Step 4: Configuring environment...${NC}"
ssh root@${SERVER_IP} << 'ENDSSH'
set -e

cd Birilium/wallet/node-backend

# Generate secure credentials
echo "Generating secure credentials..."
API_KEY=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
ADMIN_PASSWORD=$(node -e "console.log(require('crypto').randomBytes(16).toString('hex'))")
NODE_PRIVATE_KEY=$(node -e "const EC = require('elliptic').ec; const ec = new EC('secp256k1'); console.log(ec.genKeyPair().getPrivate('hex'))")

# Create .env file
cat > .env << EOF
# Birilium Seed Node Configuration
# Auto-generated by deploy script

# Server
HTTP_PORT=3001
P2P_PORT=6001
NODE_ENV=production

# Security
API_KEY=${API_KEY}
ADMIN_USERNAME=admin
ADMIN_PASSWORD=${ADMIN_PASSWORD}

# Database
MONGODB_URI=mongodb://localhost:27017
MONGODB_DB=birilium

# Blockchain
MAX_PEERS=50
ENABLE_P2P_TLS=false

# Node Identity
NODE_PRIVATE_KEY=${NODE_PRIVATE_KEY}

# Logging
LOG_LEVEL=info
LOG_FILE=./logs/node.log

# PayPal (optional - configure later if needed)
PAYPAL_MODE=live
PAYPAL_CLIENT_ID=
PAYPAL_CLIENT_SECRET=
PAYPAL_PLAN_ID=
EOF

# Create logs directory
mkdir -p logs
mkdir -p data

echo "✓ Environment configured"
echo ""
echo "==================================="
echo "SAVE THESE CREDENTIALS:"
echo "==================================="
echo "Admin Username: admin"
echo "Admin Password: ${ADMIN_PASSWORD}"
echo "API Key: ${API_KEY}"
echo "==================================="
echo ""
ENDSSH

echo -e "${GREEN}✓ Environment configured${NC}"
echo ""

# Setup firewall
echo -e "${BLUE}Step 5: Configuring firewall...${NC}"
ssh root@${SERVER_IP} << 'ENDSSH'
set -e

# Configure UFW
ufw --force reset
ufw default deny incoming
ufw default allow outgoing

# Allow SSH (IMPORTANT!)
ufw allow 22/tcp

# Allow HTTP API
ufw allow 3001/tcp

# Allow P2P
ufw allow 6001/tcp

# Enable firewall
ufw --force enable

echo "✓ Firewall configured"
ENDSSH

echo -e "${GREEN}✓ Firewall configured${NC}"
echo ""

# Start the node
echo -e "${BLUE}Step 6: Starting Birilium node...${NC}"
ssh root@${SERVER_IP} << 'ENDSSH'
set -e

cd Birilium/wallet/node-backend

# Stop old process if running
pm2 delete birilium-node 2>/dev/null || true

# Start the node
pm2 start node.js --name birilium-node --time

# Save PM2 config
pm2 save

# Setup startup script
pm2 startup systemd -u root --hp /root

echo "✓ Node started with PM2"
ENDSSH

echo -e "${GREEN}✓ Node started${NC}"
echo ""

# Verify deployment
echo -e "${BLUE}Step 7: Verifying deployment...${NC}"
sleep 5

curl -s http://${SERVER_IP}:3001/health > /dev/null && {
    echo -e "${GREEN}✓ Node is accessible at http://${SERVER_IP}:3001${NC}"
} || {
    echo -e "${RED}⚠ Node might not be accessible yet. Checking logs...${NC}"
    ssh root@${SERVER_IP} "pm2 logs birilium-node --lines 20 --nostream"
}

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}   DEPLOYMENT COMPLETE! 🎉${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Your Birilium seed node is now running!"
echo ""
echo "Node Details:"
echo "  HTTP API: http://${SERVER_IP}:3001"
echo "  P2P Port: ws://${SERVER_IP}:6001"
echo "  Health Check: http://${SERVER_IP}:3001/health"
echo ""
echo "Useful Commands:"
echo "  SSH into server: ssh root@${SERVER_IP}"
echo "  Check logs: ssh root@${SERVER_IP} 'pm2 logs birilium-node'"
echo "  Restart node: ssh root@${SERVER_IP} 'pm2 restart birilium-node'"
echo "  Check status: ssh root@${SERVER_IP} 'pm2 status'"
echo ""
echo "Next Steps:"
echo "1. Test the API: curl http://${SERVER_IP}:3001/health"
echo "2. View admin panel: http://${SERVER_IP}:3001/api/admin"
echo "3. Update wallet to connect to this seed node"
echo ""
echo "Credentials saved on server at: ~/Birilium/wallet/node-backend/.env"
echo ""
